### ISSUE TITLE
可以分享下训练数据嘛

### ISSUE THREAD

**Issue by Qianxunha** [XiShuFan/CBCT-interactive-segmentation-tool-based-on-MITK#2]
您好，可以分享下，提取牙齿ROI后，训练数据嘛

**Comment by XiShuFan** [comment]
> 您好，可以分享下，提取牙齿ROI后，训练数据嘛

数据可以在这篇工作中找到：

_A fully automatic AI system for tooth and alveolar bone segmentation from cone-beam CT images_

**Comment by Qianxunha** [comment]
> > 您好，可以分享下，提取牙齿ROI后，训练数据嘛
> 
> 数据可以在这篇工作中找到：
> 
> _用于从锥形束 CT 图像中分割牙齿和牙槽骨的全自动 AI 系统_

谢谢哥们，还有一个疑问想请教你：在全景图框选单颗牙齿，frame框选的是牙齿上的一部分？，还是frame2框选牙齿到整个牙根，如果有些牙齿歪的，斜着45度，会框选到其他牙齿部分。
![image](https://github.com/user-attachments/assets/c415d383-09da-4bc7-a0b6-dced72d1e16f)
